"""
Created base tables.

Revision ID: d8aef66ad77a
Revises:
Create Date: 2024-10-13 05:05:47.105921

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d8aef66ad77a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_order_notifications", sa.Column("id", sa.BigInteger(), nullable=False), sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "warframe_items",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("item_name", sa.Text(), nullable=False),
        sa.Column("thumb", sa.Text(), nullable=False),
        sa.Column("url_name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "warframe_market_orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("platinum_threshold", sa.Integer(), nullable=False),
        sa.Column("minimum_quantity", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["warframe_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_order_alerts_association",
        sa.Column("user_order_alert_id", sa.Integer(), nullable=False),
        sa.Column("warframe_market_order_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_order_alert_id"],
            ["user_order_notifications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warframe_market_order_id"],
            ["warframe_market_orders.id"],
        ),
        sa.PrimaryKeyConstraint("user_order_alert_id", "warframe_market_order_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_order_alerts_association")
    op.drop_table("warframe_market_orders")
    op.drop_table("warframe_items")
    op.drop_table("user_order_notifications")
    # ### end Alembic commands ###
